# Generated by Django 6.0.4 on 2026-04-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_connect_music_post_mediafile_reel_delete_mediapost'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
