# Generated by Django 6.0.4 on 2026-04-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_music_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='music_covers/'),
        ),
    ]
